"""Generated capabilities reference for mcp-council.

The tool PARAMETER schemas are already generated by the MCP SDK from the Python
signatures. What was NOT generated — and therefore drifted — was the model
catalog surfaced to callers: `model_ask`'s docstring hard-listed model ids that
could fall out of sync with `models.CATALOG`. This module derives all of that
from the real constants so a catalog edit updates the reference automatically:

  * `build_capabilities()` — one machine-readable dict (models + roles + prices,
    presets + aliases, council defaults, run limits, sandbox posture, tools).
  * `model_ask_models_line()` — the exact "Available: …" line the model_ask
    docstring uses, generated from CATALOG. A unit test asserts the docstring
    matches this, so the two can never silently diverge.

The `tools` list is read from the LIVE server registry (`registered_tools()`),
not hand-maintained. The hand-written copy it replaced had already drifted —
council_purge_logs, council_estimate, council_critique, council_critique_async
and dialogue_fork were all missing, so the discovery tool hid five capabilities
from every caller that used it to find out what the server can do.
"""

from __future__ import annotations

import models as models_mod
from models import (
    ABSOLUTE_MAX_TOKENS,
    CATALOG,
    COUNCIL_DEFAULT,
    PRESET_ALIASES,
    PRESETS,
)


def _role(model_id: str, cfg: dict) -> str:
    """council | worker | disabled — how the id is meant to be used."""
    if cfg.get("enabled") is False:
        return "disabled"
    if model_id in COUNCIL_DEFAULT:
        return "council"
    return "worker"


def model_ask_models_line() -> str:
    """The catalog-derived model list for model_ask's docstring/help.

    Enabled ids (council + worker), in CATALOG order, with disabled ones noted
    parenthetically. Single source of truth so the docstring can't drift from
    CATALOG (guarded by a unit test)."""
    enabled = [mid for mid, c in CATALOG.items() if c.get("enabled") is not False]
    disabled = [mid for mid, c in CATALOG.items() if c.get("enabled") is False]
    line = ", ".join(enabled)
    if disabled:
        line += f". ({', '.join(disabled)} — disabled.)"
    return line


def registered_tools() -> list[str]:
    """Names of every tool actually registered on the MCP server, sorted.

    Read from the live registry so `council_capabilities` cannot claim a tool
    set the server doesn't have (or omit one it does). Returns [] if the server
    module can't be imported — capabilities then reports an empty list rather
    than a plausible-looking lie."""
    try:
        import server as _srv

        return sorted(t.name for t in _srv.mcp._tool_manager.list_tools())
    except Exception:  # pragma: no cover — introspection is best-effort
        return []


def build_capabilities() -> dict:
    """Machine-readable capabilities snapshot generated from live constants."""
    # Lazy imports so this leaf module never forms an import cycle with the
    # orchestrator / server that import it.
    try:
        from council import MAX_ROUNDS
    except Exception:  # pragma: no cover
        MAX_ROUNDS = None
    try:
        from web_search_tool import MAX_RUN_SEARCHES, MAX_TOOL_ITERATIONS
    except Exception:  # pragma: no cover
        MAX_RUN_SEARCHES = MAX_TOOL_ITERATIONS = None
    try:
        from state import MAX_ACTIVE_JOBS
    except Exception:  # pragma: no cover
        MAX_ACTIVE_JOBS = None
    try:
        import server as _srv
        request_token_cap = getattr(_srv, "MAX_RESPONSE_TOKENS_HARD_CAP", None)
    except Exception:  # pragma: no cover
        request_token_cap = None

    model_rows = []
    for mid, cfg in CATALOG.items():
        model_rows.append({
            "id": mid,
            "model": cfg.get("model"),
            "provider": cfg.get("provider"),
            "role": _role(mid, cfg),
            "enabled": cfg.get("enabled") is not False,
            "price_in_usd_per_1m": cfg.get("price_in"),
            "price_out_usd_per_1m": cfg.get("price_out"),
            "min_max_tokens": cfg.get("min_max_tokens"),
        })

    return {
        "service": "mcp-council",
        "models": model_rows,
        "council_default": list(COUNCIL_DEFAULT),
        "presets": {name: list(ids) for name, ids in PRESETS.items()},
        "preset_aliases": dict(PRESET_ALIASES),
        "provider_domains": sorted(
            {c.get("provider") for c in CATALOG.values() if c.get("provider")}
        ),
        "limits": {
            "max_rounds": MAX_ROUNDS,
            "request_token_cap": request_token_cap,
            "absolute_max_tokens": ABSOLUTE_MAX_TOKENS,
            "max_tool_iterations_per_member": MAX_TOOL_ITERATIONS,
            "max_run_web_searches": MAX_RUN_SEARCHES,
            "max_active_async_jobs": MAX_ACTIVE_JOBS,
        },
        # Live server registry — never a hand-maintained copy (see module docstring).
        "tools": registered_tools(),
        "verdict_axes": [
            "agreement_confidence", "quorum_ok", "independent_votes",
            "winner_ranked_by", "provider_domains", "evidence",
            "evidence_domains", "risk_class", "human_review_required",
            "ranking_methods_agree", "incomplete_rankings", "stop_reason",
        ],
    }
